---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - answerfile_TPM_Lab.yml
  tasks:
  - name: Gather vCenter MOIDs PG
    vcenter_gather_moids:
      hostname: 'vc01.yves.local'
      username: 'administrator@yves.local'
      password: 'VMware1!'
      datacenter_name: 'tpm-lab'
      portgroup_name: vlan41
      validate_certs: False
    register: gather_moid_pg
  - name: Gather vCenter UUID VM
    vcenter_gather_moids:
      hostname: 'vc01.yves.local'
      username: 'administrator@yves.local'
      password: 'VMware1!'
      datacenter_name: 'tpm-lab'
      virtualmachine_name: test-rhel72-lcp
      validate_certs: False
    register: gather_uuid_vm

  - debug: msg="The searched VM uuid is {{ gather_uuid_vm.object_uuid }}"
  - debug: msg="The searched PG moid is {{ gather_moid_pg.object_id }}"

- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - answerfile_TPM_Lab.yml
  tasks:
  - name: vm switch migrate
    nsx_attach_vm_switch:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      object_moid: "{{ gather_uuid_vm.object_uuid }}"
      logicalswitch: test_ls
      # portgroup_id: "{{ gather_moid_pg.object_id }}"
    register: create_logical_switch

  - debug: var=create_logical_switch
