---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - answerfile_old_nsxman.yml
  tasks:
  - name: nsx_logical_switch Operation
    nsx_logical_switch:
      nsxmanager_spec: "{{ nsxmanager_spec }}"
      state: present
      transportzone: "TZ"
      name: "TestLS"
      controlplanemode: "UNICAST_MODE"
      description: "My Great Logical Switch"
    register: create_logical_switch

  #- debug: var=create_logical_switch
